### ISSUE TITLE
Not showing the correct today as today

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/pretty_calendar#13]
See screenshot. It's November 14th (about 7:00pm in Minnesota), but calendar is showing it as the 15th. 

I checked and the site time zone is correct. Having done any additional debugging yet. Will try to come back to this one soon.

![image](https://user-images.githubusercontent.com/3144571/141706315-6fd9e0c1-01c0-4a38-928a-77689dff5179.png)

**Comment by laryn** [comment]
I'm guessing it is somehow timezone related, I've been chasing a few strange timezone issues now and then...

**Comment by laryn** [comment]
@stpaultim I think I've solved this one.
