### ISSUE TITLE
incorrect date issue

### ISSUE THREAD

**Issue by john-haus** [backdrop-contrib/pretty_calendar#15]
I'm having an odd issue with a particular date and Pretty Calendars. On a site I'm developing (pky.hmgdev.com) if I try to add an event for January 20th, 2023 it is not shown in the pretty Celandar on the homepage. Moreover there is now an event shown for the 21st, which doesn't exist. If you click on the 21st, it'll show you that now events are listed.  In month view, the events is correctly show on the 20th, which makes me think it is something to do with Pretty Calendars.  I have tried deleting and re-creating the event but to no avail.  I'd really appreciate some input if possible!

**Comment by argiepiano** [comment]
So, here's a clue. The event on January 20 ends late, 9pm. My guess is that the module is not taking into account the timezone of your site (check to be sure you have set a timezone at `admin/config/regional/settings`). So, it's probably using UTC, which is 5 hours ahead from Kentucky. So, the code in charge of highlighting the date on the Calendar is highlighting the next day, while the menu callback to list the nodes on a specific date is working correctly. 

The same thing is happening to your event on January 12. It's a late event, and shows up in the Calendar on 1.13. But if you go to `https://pky.hmgdev.com/calendar/2023/01/12` you'll see it in the list.

**Comment by john-haus** [comment]
I agree it's something to do with the timezone - which is set on the site by the way. It's odd that the end time would move it over to the next day and not the start time - I'll try having a look.  Thanks!

**Comment by argiepiano** [comment]
The start time for those events is 6pm. If you add 5 hours, that brings the both the start and end time to the next day in UTC. Since you have set up the timezone, then this must be a bug with the module.

**Comment by laryn** [comment]
@padprint Sorry I missed this when it was first filed. I'm doing a little work on this module in the next month or two and I'll try to keep an eye out for this.

**Comment by laryn** [comment]
I think this one may be a duplicate that was fixed a few months back.
https://github.com/backdrop-contrib/pretty_calendar/issues/13

**Comment by laryn** [comment]
For the record, I just added a commit that accounts for the timezone offset more fully, which is likely related to this issue.
