### ISSUE TITLE
display links to events not working

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/pretty_calendar#5]
I cannot make work the "display links to events" tooltyp option. It always displays the number of events.

**Comment by laryn** [comment]
@robertgarrigos I'll try to test when I get a chance. Thanks for the report.

**Comment by laryn** [comment]
@robertgarrigos 
I think I may have been a little over-eager in dumping some ancient tooltip code... Either will need to replace/port that or see if it can be done differently.

**Comment by laryn** [comment]
@robertgarrigos I don't know if you're still using this module, but if so you may be interested in trying out the PR linked here. It reworks the day template quite a lot so if you've customized that, you will need to adjust it or revert to defaults there.

The big change is that it refreshes the told "display links to events in the tooltip" functionality with a new approach -- the calendar can either link directly to the listing page, or display events in a modal dialog.

**Comment by laryn** [comment]
Follow-up: I merged into a new 1.x-2.x branch that I'll be making some adjustments to before I release, but feel free to test this there.

**Comment by robertgarrigos** [comment]
@laryn No, I'm not using it, but just test it. Basis theme doesn't seem to work. Also, Dates format doesn't seem to work either: it always shows a full date, despite the format I choose. Modal pop up doesn't seem to work...

Now I see what's happening: I was testing 1.x-1.2.x head, which seems to be broken. 1.x-1.2.1 release just do the same as before: display links to events tooltip shows count of events.
