### ISSUE TITLE
Events in Basis for Backdrop theme not bold

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/pretty_calendar#7]
Out of curiosity, I've had a quick look at the module and saw that calendar events are not noticeable (not bold) when the calendar is set to the only non-legacy theme ,"Basis for Backdrop".

I guess the [bold font-weight](https://github.com/backdrop-contrib/pretty_calendar/blob/1.x-1.x/themes/basis/calendar.css#L53) for `.pretty-calendar-week a` doesn't apply due to the [normal font-weight](https://github.com/backdrop-contrib/pretty_calendar/blob/1.x-1.x/themes/basis/calendar.css#L46) for .pretty-calendar-week .calendar-value.

**Comment by laryn** [comment]
Thanks @olafgrabienski ! Good catch.

The CSS for sure needs some more major reworking as well. This is mostly taking one of the legacy themes and tweaking slightly so it doesn't look _quite_ so dated.

**Comment by laryn** [comment]
Thanks @olafgrabienski -- I've removed the `font-weight: normal;` bit which didn't seem to do anything anyway. Also made the links the same color as default links in Basis, and set that new theme as the default instead of a legacy theme.
