### ISSUE TITLE
Month timestamp incorrect for timezones ahead of GMT

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/pretty_calendar#8]
Will only jump 2 months back - not one - no forward jumping.
So, at this point useless for me, but maybe I am overlooking something.

**Comment by laryn** [comment]
You are using the latest version, I assume? I am using this on a site and not seeing this -- can you provide steps to reproduce?

**Comment by Egmund** [comment]
Brand new install. 1.x-1.1.0
I simply installed it through the site's 'install new module' and set the block on a page. I took it out of maintenance mode for your enjoyment: https://bdrop.buddhistisksamfund.dk/

**Comment by Egmund** [comment]
I tried installing it on another site - same problems
What is this:
`Debug:

1548975600

i pretty_calendar_block_content() (linje 320 af /home/gudsrige/public_html/modules/pretty_calendar/pretty_calendar.module).`

**Comment by laryn** [comment]
Looks like there are some commits that aren't in the latest release. (The line you mention is probably what was cleaned up in https://github.com/backdrop-contrib/pretty_calendar/commit/6c73395818c8a61036b93d3fcc6ce12b045be0d5).

I'll do a test to see if I can replicate on a fresh install as you describe.

**Comment by laryn** [comment]
I determined that the month timestamp was being taken for GMT so timezones ahead of GMT were getting last month as the current month timestamp for the arrows -- this meant that "previous" was actually two months ago and "next" was actually current (so no change was noted when next was clicked).

I just made a new release.

**Comment by Egmund** [comment]
Thank you Laryn. That part works now. But there are other problems. I think I will stick with Fullcalendar which 'does the trick'.
