### ISSUE TITLE
View is not updated to show correct content types

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/pretty_calendar#9]
When I add an event, the calendar shows an event on the correct date. 

But, when I click on the date it shows me a view with no results. It turns out that the view is only showing "pages" despite the fact that I've selected "events" in the block settings. 

I assume that the filter on the view is supposed to be automatically updated to reflect the settings in the block?

If this is difficult, we could at least add some notes in the Readme that instruct the user to manually update their view.

**Comment by stpaultim** [comment]
I submitted a PR to fix this. The PR removes the default filter on the view set to filter for Pages. 

As far as I can tell, the module uses views_embed_view to embed that view on the page, but does not override the content type filter. 

In some testing, I don't see anything else that is breaking when I remove that filter. But, it might be good to do some more testing.

To properly test the fix you must uninstall the module and delete the existing view, before re-enabling the module. 

@laryn

**Comment by laryn** [comment]
Thanks @stpaultim -- yes, the view has been shoehorned into what was the existing functionality, which calculates all the content IDs and feeds those into a view for display, so you are right that we don't need to enforce a content type restriction on the view.
